---
abstract: 'remove cookies from the requests'
author:
  - 'Wallace Reis <wreis@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Plack::Builder: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Session-RemoveCookies
requires:
  HTTP::Headers::Util: 0
  Plack::Middleware: 0
  Plack::Request: 0
  Plack::Util::Accessor: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/wreis/Plack-Middleware-Session-RemoveCookies.git
version: 0.011
